Attribute VB_Name = "SystemCore"
' ===================================================================
' WINDOWS API FUNCTIONS (CLAUDE.md: 32/64-bit compatibility)
' ===================================================================

' **Purpose**: Windows API declarations for getting current user name
' **Dependencies**: advapi32.dll
' **CLAUDE.md DUAL DEPLOYMENT**: PtrSafe cannot be backwards compatible
' **DEPLOYMENT STRATEGY**: Create two separate system versions
'
' IMPORTANT: This module must be deployed in two versions:
' 1. SystemCore_32bit.bas - For 32-bit Excel deployment
' 2. SystemCore_64bit.bas - For 64-bit Excel deployment
'
' CURRENT VERSION: 64-bit Excel (with PtrSafe)
' FOR 32-BIT: Use SystemCore32.bas instead

' =============== ACTIVE VERSION: 64-BIT EXCEL ===============
Private Declare PtrSafe Function GetUserName Lib "advapi32.dll" Alias "GetUserNameA" _
    (ByVal lpBuffer As String, ByRef nSize As Long) As Long

' **Purpose**: Core system infrastructure combining CoreFramework, ValidationFramework, and API functions
' **CLAUDE.md Compliance**: Maintains 32/64-bit compatibility, preserves all legacy functionality
' **Consolidation**: Combines CoreFramework.bas, ValidationFramework.bas, GetUserName32.bas, GetUserName64.bas
Option Explicit

' ===================================================================
' DATA TYPES (CLAUDE.md: Document all Type definitions)
' ===================================================================

' **Purpose**: Complete enquiry information structure for PCS system
' **CLAUDE.md Compliance**: Maintains all legacy enquiry fields for compatibility
Public Type EnquiryData
    ' **Purpose**: Unique enquiry identifier in E00001 format
    ' **Dependencies**: Generated by DataOperations.GetNextEnquiryNumber()
    EnquiryNumber As String

    ' **Purpose**: Customer company name for business identification
    ' **Side Effects**: Used in search database, customer file creation
    CustomerName As String

    ' **Purpose**: Primary contact person at customer company
    ContactPerson As String

    ' **Purpose**: Customer company phone number
    CompanyPhone As String

    ' **Purpose**: Customer company fax number (legacy compatibility)
    CompanyFax As String

    ' **Purpose**: Customer email address for communication
    Email As String

    ' **Purpose**: Description of component being enquired about
    ' **Dependencies**: Used in search keywords, quote generation
    ComponentDescription As String

    ' **Purpose**: Internal component code if available
    ComponentCode As String

    ' **Purpose**: Material grade specification for component
    MaterialGrade As String

    ' **Purpose**: Quantity of components requested
    ' **Errors**: Must be > 0, validated by BusinessLogic.ValidateEnquiryData()
    Quantity As Long

    ' **Purpose**: Date enquiry was created
    ' **Side Effects**: Used for search sorting, archival decisions
    DateCreated As Date

    ' **Purpose**: Full path to enquiry Excel file
    ' **Dependencies**: Generated by DataOperations file operations
    FilePath As String

    ' **Purpose**: Searchable keywords for enquiry
    ' **Dependencies**: Used by BusinessLogic for record finding
    SearchKeywords As String
End Type

' **Purpose**: Complete quote information structure for PCS system
' **CLAUDE.md Compliance**: Maintains all legacy quote fields for compatibility
Public Type QuoteData
    ' **Purpose**: Unique quote identifier in Q00001 format
    ' **Dependencies**: Generated by DataOperations.GetNextQuoteNumber()
    QuoteNumber As String

    ' **Purpose**: Reference to source enquiry
    ' **Dependencies**: Links to EnquiryData.EnquiryNumber
    EnquiryNumber As String

    ' **Purpose**: Customer company name (inherited from enquiry)
    CustomerName As String

    ' **Purpose**: Component description (inherited from enquiry)
    ComponentDescription As String

    ' **Purpose**: Component code (inherited from enquiry)
    ComponentCode As String

    ' **Purpose**: Material grade (inherited from enquiry)
    MaterialGrade As String

    ' **Purpose**: Quantity being quoted (inherited from enquiry)
    Quantity As Long

    ' **Purpose**: Price per unit in local currency
    ' **Errors**: Must be > 0, validated by BusinessLogic.ValidateQuoteData()
    UnitPrice As Currency

    ' **Purpose**: Total quote value (UnitPrice * Quantity)
    ' **Side Effects**: Used for job costing, customer invoicing
    TotalPrice As Currency

    ' **Purpose**: Manufacturing lead time description
    LeadTime As String

    ' **Purpose**: Quote expiration date
    ' **Side Effects**: Used for quote validity checking
    ValidUntil As Date

    ' **Purpose**: Date quote was created
    DateCreated As Date

    ' **Purpose**: Full path to quote Excel file
    ' **Dependencies**: Generated by DataOperations file operations
    FilePath As String

    ' **Purpose**: Quote status (Pending, Accepted, Rejected)
    Status As String
End Type

' **Purpose**: Complete job information structure for PCS system
' **CLAUDE.md Compliance**: Maintains all legacy job fields for compatibility
Public Type JobData
    ' **Purpose**: Unique job identifier in J00001 format
    ' **Dependencies**: Generated by DataOperations.GetNextJobNumber()
    JobNumber As String

    ' **Purpose**: Reference to source quote
    ' **Dependencies**: Links to QuoteData.QuoteNumber
    QuoteNumber As String

    ' **Purpose**: Customer company name (inherited from quote)
    CustomerName As String

    ' **Purpose**: Component description (inherited from quote)
    ComponentDescription As String

    ' **Purpose**: Component code (inherited from quote)
    ComponentCode As String

    ' **Purpose**: Material grade (inherited from quote)
    MaterialGrade As String

    ' **Purpose**: Quantity to manufacture (inherited from quote)
    Quantity As Long

    ' **Purpose**: Customer requested due date
    DueDate As Date

    ' **Purpose**: Workshop internal due date
    ' **Side Effects**: Used for production scheduling
    WorkshopDueDate As Date

    ' **Purpose**: Customer delivery due date
    CustomerDueDate As Date

    ' **Purpose**: Job order value (inherited from quote)
    OrderValue As Currency

    ' **Purpose**: Date job was created
    DateCreated As Date

    ' **Purpose**: Full path to job Excel file
    ' **Dependencies**: Generated by DataOperations file operations
    FilePath As String

    ' **Purpose**: Current job status (Active, On Hold, Completed, Cancelled)
    Status As String

    ' **Purpose**: Operator assigned to this job
    ' **Side Effects**: Used for WIP reporting, resource allocation
    AssignedOperator As String

    ' **Purpose**: Manufacturing operations required
    Operations As String

    ' **Purpose**: File paths to job pictures/drawings
    Pictures As String

    ' **Purpose**: Additional job notes and comments
    Notes As String

    ' **Purpose**: Customer's order number for this job (required for quote acceptance)
    ' **Form Usage**: Populated from FAcceptQuote.CustomerOrderNumber
    CustomerOrderNumber As String

    ' **Purpose**: Job urgency level (NORMAL, URGENT, BREAK DOWN)
    ' **Form Usage**: Populated from FAcceptQuote.Job_Urgency
    JobUrgency As String

    ' **Purpose**: Job lead time in days
    ' **Form Usage**: Populated from FAcceptQuote.Job_LeadTime
    JobLeadTime As Long

    ' **Purpose**: Date when job work should start
    ' **Form Usage**: Populated from FAcceptQuote.Job_StartDate
    JobStartDate As Date

    ' **Purpose**: Sequence number for multi-part jobs (1, 2, 3, etc.)
    ' **Form Usage**: Populated from FAcceptQuote.Compilation_SequenceNumber
    CompilationSequenceNumber As Long

    ' **Purpose**: Total number of parts in multi-part job
    ' **Form Usage**: Populated from FAcceptQuote.Compilation_TotalNumber
    CompilationTotalNumber As Long

    ' **Purpose**: Contact person for this job (inherited from quote)
    ContactPerson As String

    ' **Purpose**: Company phone number (inherited from quote)
    CompanyPhone As String

    ' **Purpose**: Company fax number (inherited from quote)
    CompanyFax As String

    ' **Purpose**: Company email address (inherited from quote)
    Email As String

    ' **Purpose**: Work instructions for operators
    WorkInstructions As String

    ' **Purpose**: Search keywords for database lookups
    SearchKeywords As String
End Type

' **Purpose**: Contract template information structure for PCS system
' **CLAUDE.md Compliance**: Maintains all legacy contract fields for compatibility
Public Type ContractData
    ' **Purpose**: Contract template name identifier
    ContractName As String

    ' **Purpose**: Customer this contract template applies to
    CustomerName As String

    ' **Purpose**: Standard component description for this contract
    ComponentDescription As String

    ' **Purpose**: Standard operations for this contract type
    StandardOperations As String

    ' **Purpose**: Standard lead time for this contract
    LeadTime As String

    ' **Purpose**: Full path to contract template Excel file
    ' **Dependencies**: Generated by DataOperations file operations
    FilePath As String

    ' **Purpose**: Date contract template was created
    DateCreated As Date

    ' **Purpose**: Date contract was last used for job creation
    ' **Side Effects**: Used for contract usage tracking
    LastUsed As Date
End Type

' **Purpose**: Search record structure for database operations
' **CLAUDE.md Compliance**: Maintains all search functionality requirements
Public Type SearchRecord
    ' **Purpose**: Type of record (Enquiry, Quote, Job, Contract)
    ' **Dependencies**: Must match RecordType enum values
    RecordType As String

    ' **Purpose**: Record number (E00001, Q00001, J00001, etc.)
    RecordNumber As String

    ' **Purpose**: Customer name for this record
    CustomerName As String

    ' **Purpose**: Description/component for this record
    Description As String

    ' **Purpose**: Date record was created
    ' **Side Effects**: Used for search result sorting
    DateCreated As Date

    ' **Purpose**: Full file path to record Excel file
    FilePath As String

    ' **Purpose**: Searchable keywords for this record
    ' **Dependencies**: Used by BusinessLogic search algorithms
    Keywords As String
End Type

' **Purpose**: System configuration structure
' **CLAUDE.md Compliance**: New structure for system management
Public Type SystemConfig
    ' **Purpose**: Root directory path for PCS system
    RootPath As String

    ' **Purpose**: Current user information
    CurrentUser As String

    ' **Purpose**: Excel version compatibility mode
    ExcelVersion As String

    ' **Purpose**: System initialization status
    IsInitialized As Boolean

    ' **Purpose**: Last system validation timestamp
    LastValidated As Date
End Type

' ===================================================================
' ENUMS (CLAUDE.md: Document all enumeration values)
' ===================================================================

' **Purpose**: Record type enumeration for PCS system
Public Enum RecordType
    rtEnquiry = 1    ' **Purpose**: Enquiry records
    rtQuote = 2      ' **Purpose**: Quote records
    rtJob = 3        ' **Purpose**: Job records
    rtContract = 4   ' **Purpose**: Contract templates
End Enum

' **Purpose**: Job status enumeration for workflow management
Public Enum JobStatus
    jsActive = 1     ' **Purpose**: Job is currently active
    jsOnHold = 2     ' **Purpose**: Job is temporarily on hold
    jsCompleted = 3  ' **Purpose**: Job has been completed
    jsCancelled = 4  ' **Purpose**: Job has been cancelled
End Enum

' ===================================================================
' ERROR HANDLING (CLAUDE.md: Document recovery steps)
' ===================================================================

' **Purpose**: Standard error codes for PCS system
' **CLAUDE.md Compliance**: Maintains all error handling patterns
Public Const ERR_FILE_NOT_FOUND As Long = 53
Public Const ERR_PATH_NOT_FOUND As Long = 76
Public Const ERR_PERMISSION_DENIED As Long = 70
Public Const ERR_DISK_FULL As Long = 61
Public Const ERR_EXCEL_NOT_AVAILABLE As Long = 429
Public Const ERR_WORKBOOK_OPEN As Long = 1004
Public Const ERR_INVALID_REFERENCE As Long = 1004

' **Purpose**: Centralized error logging with file output
' **Parameters**:
'   - ErrorNumber (Long): The error number that occurred
'   - ErrorDescription (String): Description of the error
'   - ProcedureName (String): Name of procedure where error occurred
'   - ModuleName (String, Optional): Name of module where error occurred
' **Returns**: None (Subroutine)
' **Dependencies**: File system access for error logging
' **Side Effects**: Creates/appends to error_log.txt file
' **Errors**: Displays critical error message if logging fails
' **CLAUDE.md Compliance**: Centralized error management with logging
Public Sub LogError(ByVal ErrorNumber As Long, ByVal ErrorDescription As String, ByVal ProcedureName As String, Optional ByVal ModuleName As String = "")
    Dim ErrorMsg As String
    Dim LogPath As String
    Dim FileNum As Integer

    On Error GoTo ErrorLogging_Error

    ErrorMsg = Format(Now, "dd/mm/yyyy hh:mm:ss") & " - "
    If ModuleName <> "" Then ErrorMsg = ErrorMsg & ModuleName & "."
    ErrorMsg = ErrorMsg & ProcedureName & " - Error " & ErrorNumber & ": " & ErrorDescription

    LogPath = ThisWorkbook.Path & "\error_log.txt"

    FileNum = FreeFile
    Open LogPath For Append As #FileNum
    Print #FileNum, ErrorMsg
    Close #FileNum

    Exit Sub

ErrorLogging_Error:
    MsgBox "Critical Error: Unable to log error to file." & vbCrLf & _
           "Original Error: " & ErrorNumber & " - " & ErrorDescription, vbCritical
End Sub

' **Purpose**: Handle standard errors with user-friendly messages and logging
' **Parameters**:
'   - ErrorNumber (Long): The error number to handle
'   - ProcedureName (String): Name of procedure where error occurred
'   - ModuleName (String, Optional): Name of module where error occurred
' **Returns**: Boolean - True if error was handled, False if unrecognized
' **Dependencies**: LogError for error logging, MsgBox for user notification
' **Side Effects**: Logs error to file, displays user message
' **Errors**: Returns False for unrecognized error numbers
' **CLAUDE.md Compliance**: Standardized error handling with recovery guidance
Public Function HandleStandardErrors(ByVal ErrorNumber As Long, ByVal ProcedureName As String, Optional ByVal ModuleName As String = "") As Boolean
    Dim UserMsg As String

    Select Case ErrorNumber
        Case ERR_FILE_NOT_FOUND
            UserMsg = "File not found. Please check the file path and try again."
        Case ERR_PATH_NOT_FOUND
            UserMsg = "Directory not found. Please verify the directory structure."
        Case ERR_PERMISSION_DENIED
            UserMsg = "Access denied. Please check file permissions or close any open files."
        Case ERR_DISK_FULL
            UserMsg = "Disk full. Please free up space and try again."
        Case ERR_EXCEL_NOT_AVAILABLE
            UserMsg = "Excel application is not available. Please ensure Excel is properly installed."
        Case ERR_WORKBOOK_OPEN
            UserMsg = "Unable to open workbook. File may be in use or corrupted."
        Case Else
            HandleStandardErrors = False
            Exit Function
    End Select

    LogError ErrorNumber, Err.Description, ProcedureName, ModuleName
    MsgBox UserMsg & vbCrLf & vbCrLf & "Technical Details: Error " & ErrorNumber, vbExclamation
    HandleStandardErrors = True
End Function

' **Purpose**: Clear the current error state
' **Parameters**: None
' **Returns**: None (Subroutine)
' **Dependencies**: VBA Err object
' **Side Effects**: Clears Err.Number and Err.Description
' **Errors**: None
Public Sub ClearError()
    Err.Clear
End Sub

' **Purpose**: Get formatted string of last error information
' **Parameters**: None
' **Returns**: String - Formatted error information
' **Dependencies**: VBA Err object
' **Side Effects**: None
' **Errors**: Returns empty string if no error
Public Function GetLastErrorInfo() As String
    If Err.Number <> 0 Then
        GetLastErrorInfo = "Error " & Err.Number & ": " & Err.Description
    Else
        GetLastErrorInfo = ""
    End If
End Function

' **Purpose**: Get current Windows username using appropriate API
' **Original**: Interface_VBA/GetUserName32.bas, GetUserName64.bas
' **Parameters**: None
' **Returns**: String - Current Windows username
' **Dependencies**: Windows API (advapi32.dll)
' **Side Effects**: None
' **Errors**: Returns "Unknown" if API call fails
' **CLAUDE.md Compliance**: Dual deployment strategy - no conditional compilation
Public Function Get_User_Name() As String
    Dim UserName As String
    Dim UserNameSize As Long

    On Error GoTo Error_Handler

    UserNameSize = 255
    UserName = Space(255)

    If GetUserName(UserName, UserNameSize) <> 0 Then
        Get_User_Name = Left$(UserName, UserNameSize - 1)
    Else
        Get_User_Name = "Unknown"
    End If
    Exit Function

Error_Handler:
    Get_User_Name = "Unknown"
End Function

' **Purpose**: Alternative user name function for compatibility
' **Returns**: String - Current Windows username (same as Get_User_Name)
' **CLAUDE.md Compliance**: Maintains exact function signatures from original system
Public Function GetCurrentUser() As String
    On Error GoTo Error_Handler

    GetCurrentUser = Get_User_Name()

    ' Ensure we have a valid username
    If GetCurrentUser = "" Then
        GetCurrentUser = "Unknown User"
    End If

    Exit Function

Error_Handler:
    LogError Err.Number, Err.Description, "GetCurrentUser", "SystemCore"
    GetCurrentUser = "Unknown User"
End Function

' **Purpose**: Display warning message to user
' **Parameters**:
'   - Message (String): Warning message to display
'   - Title (String): Title for message box
' **Returns**: None (Subroutine)
' **Dependencies**: VBA MsgBox
' **Side Effects**: Displays message box to user
' **Errors**: None
Public Sub ShowWarning(ByVal Message As String, ByVal Title As String)
    MsgBox Message, vbExclamation + vbOKOnly, Title
End Sub

' **Purpose**: Display error message to user
' **Parameters**:
'   - Message (String): Error message to display
'   - Title (String): Title for message box
' **Returns**: None (Subroutine)
' **Dependencies**: VBA MsgBox
' **Side Effects**: Displays message box to user
' **Errors**: None
Public Sub ShowError(ByVal Message As String, ByVal Title As String)
    MsgBox Message, vbCritical + vbOKOnly, Title
End Sub

' **Purpose**: Display information message to user
' **Parameters**:
'   - Message (String): Information message to display
'   - Title (String): Title for message box
' **Returns**: None (Subroutine)
' **Dependencies**: VBA MsgBox
' **Side Effects**: Displays message box to user
' **Errors**: None
Public Sub ShowInformation(ByVal Message As String, ByVal Title As String)
    MsgBox Message, vbInformation + vbOKOnly, Title
End Sub

' **Purpose**: Display question to user and get response
' **Parameters**:
'   - Message (String): Question to display
'   - Title (String): Title for message box
' **Returns**: Long - User response (vbYes, vbNo, etc.)
' **Dependencies**: VBA MsgBox
' **Side Effects**: Displays message box to user
' **Errors**: Returns vbNo on error
Public Function ShowQuestion(ByVal Message As String, ByVal Title As String) As Long
    On Error Resume Next
    ShowQuestion = MsgBox(Message, vbQuestion + vbYesNo, Title)
    If Err.Number <> 0 Then ShowQuestion = vbNo
    On Error GoTo 0
End Function

' ===================================================================
' SYSTEM UTILITIES (CLAUDE.md: 32/64-bit compatibility)
' ===================================================================

' **Purpose**: Validate all system requirements for PCS operation
' **Parameters**: None
' **Returns**: Boolean - True if all requirements met, False if issues found
' **Dependencies**: Excel application object, file system access
' **Side Effects**: Logs validation results to error log
' **Errors**: Returns False on validation failure, logs specific issues
' **CLAUDE.md Compliance**: Replaces legacy Check_Dir.bas functionality
Public Function ValidateSystemRequirements() As Boolean
    Dim ExcelVersion As String
    Dim UserName As String
    Dim RootPath As String

    On Error GoTo Error_Handler

    ' Check Excel version compatibility
    ExcelVersion = Application.Version
    If Val(ExcelVersion) < 12 Then
        LogError 0, "Excel version " & ExcelVersion & " may not be fully compatible", "ValidateSystemRequirements", "SystemCore"
    End If

    ' Check user authentication
    UserName = GetCurrentUser()
    If UserName = "" Then
        LogError 0, "Unable to determine current user", "ValidateSystemRequirements", "SystemCore"
        ValidateSystemRequirements = False
        Exit Function
    End If

    ' Check root path availability
    RootPath = ThisWorkbook.Path
    If RootPath = "" Then
        LogError ERR_PATH_NOT_FOUND, "Unable to determine workbook path", "ValidateSystemRequirements", "SystemCore"
        ValidateSystemRequirements = False
        Exit Function
    End If

    ValidateSystemRequirements = True
    Exit Function

Error_Handler:
    LogError Err.Number, Err.Description, "ValidateSystemRequirements", "SystemCore"
    ValidateSystemRequirements = False
End Function


' **Purpose**: Remove invalid characters from string for data processing (exact legacy compatibility)
' **Parameters**:
'   - InputString (String): String to process
' **Returns**: String - String with invalid characters removed
' **Dependencies**: None
' **Side Effects**: None
' **Errors**: Returns empty string if input is empty
' **CLAUDE.md Compliance**: Exact replacement for legacy RemoveCharacters.bas Remove_Characters function
Public Function RemoveInvalidCharacters(ByVal InputString As String) As String
    Dim i As Integer
    Dim Result As String

    If InputString = "" Then
        RemoveInvalidCharacters = ""
        Exit Function
    End If

    Result = InputString

    ' Remove problematic characters for data processing (exact legacy algorithm)
    For i = 1 To Len(Result)
        If Mid(Result, i, 1) = "/" Or Mid(Result, i, 1) = ":" Or Mid(Result, i, 1) = " " Then
            Result = Mid(Result, 1, i - 1) & Mid(Result, i + 1, Len(Result) - i)
            ' DO NOT adjust i - matches legacy behavior exactly
        End If
    Next i

    RemoveInvalidCharacters = Result
End Function

' **Purpose**: Format text for display by converting underscores and case changes to spaces (exact legacy compatibility)
' **Parameters**:
'   - InputString (String): String to format for display
' **Returns**: String - Formatted string with improved readability
' **Dependencies**: None
' **Side Effects**: None
' **Errors**: Returns empty string if input is empty
' **CLAUDE.md Compliance**: Exact replacement for legacy RemoveCharacters.bas Insert_Characters function
Public Function FormatDisplayText(ByVal InputString As String) As String
    Dim i As Integer
    Dim j As Integer
    Dim Result As String

    If InputString = "" Then
        FormatDisplayText = ""
        Exit Function
    End If

    Result = InputString
    j = Len(Result)
    i = 0

    ' Process string from second character to end (exact legacy algorithm)
    For i = 2 To j
        If Mid(Result, i, 1) = "_" Then
            Result = Mid(Result, 1, i - 1) & " " & Mid(Result, i + 1, Len(Result) - i)
            i = i + 1
        Else
            If UCase(Mid(Result, i, 1)) = Mid(Result, i, 1) Then
                Result = Mid(Result, 1, i - 1) & " " & Mid(Result, i, Len(Result) - i + 1)
                j = j + 1
                i = i + 1
            End If
        End If
    Next i

    ' Remove "Component " prefix if present (exact legacy logic)
    If InStr(1, Result, "Component ", vbTextCompare) > 0 Then
        Result = Right(Result, Len(Result) - Len("Component "))
    End If

    FormatDisplayText = Result
End Function

' **Purpose**: Get system configuration information
' **Parameters**: None
' **Returns**: SystemConfig - Current system configuration
' **Dependencies**: GetCurrentUser, Application object, ThisWorkbook
' **Side Effects**: None
' **Errors**: Returns default values on error, logs issues
Public Function GetSystemConfig() As SystemConfig
    Dim Config As SystemConfig

    On Error GoTo Error_Handler

    With Config
        .RootPath = ThisWorkbook.Path
        .CurrentUser = GetCurrentUser()
        .ExcelVersion = Application.Version
        .IsInitialized = True
        .LastValidated = Now
    End With

    GetSystemConfig = Config
    Exit Function

Error_Handler:
    LogError Err.Number, Err.Description, "GetSystemConfig", "SystemCore"
    ' Return default configuration
    With Config
        .RootPath = ""
        .CurrentUser = ""
        .ExcelVersion = ""
        .IsInitialized = False
        .LastValidated = Now
    End With
    GetSystemConfig = Config
End Function

' **Purpose**: Clean filename for safe file system usage
' **Parameters**:
'   - FileName (String): Raw filename to clean
' **Returns**: String - Cleaned filename safe for file system
' **Dependencies**: None
' **Side Effects**: None
' **Errors**: Returns empty string if input is empty
Public Function CleanFileName(ByVal FileName As String) As String
    Dim Result As String
    Dim i As Integer
    Dim InvalidChars As String

    Result = Trim(FileName)
    If Result = "" Then
        CleanFileName = ""
        Exit Function
    End If

    ' Remove invalid file system characters
    InvalidChars = "\/:*?""<>|"
    For i = 1 To Len(InvalidChars)
        Result = Replace(Result, Mid(InvalidChars, i, 1), "_")
    Next i

    ' Limit length to 50 characters for compatibility
    If Len(Result) > 50 Then
        Result = Left(Result, 50)
    End If

    CleanFileName = Result
End Function

' ===================================================================
' DIRECTORY OPERATIONS (CLAUDE.md: Maintain directory functionality)
' ===================================================================

' **Purpose**: Check if directory exists, create if missing, and change to it (exact legacy compatibility)
' **Parameters**:
'   - Direc (String): Directory path to check/create
' **Returns**: None (Subroutine)
' **Dependencies**: VBA Dir, MkDir, ChDir functions
' **Side Effects**: Creates directory if missing, changes current directory
' **Errors**: May raise error if directory creation/access fails
' **CLAUDE.md Compliance**: Exact replacement for legacy Check_Dir.bas CheckDir function
Public Function CheckDir(ByVal Direc As String)
    On Error GoTo Error_Handler

    If Dir(Direc, vbDirectory) = "" Then
        MkDir (Direc)
        ChDir (Direc)
    Else
        ChDir (Direc)
    End If

    Exit Function

Error_Handler:
    LogError Err.Number, Err.Description, "CheckDir", "SystemCore"
End Function

' ===================================================================
' VALIDATION FRAMEWORK (CLAUDE.md: Standardized popup validation)
' ===================================================================

' **Purpose**: Validates required field and shows popup if empty
' **Parameters**:
'   - fieldValue (Variant): Value to validate
'   - fieldName (String): Display name for field in error message
'   - setFocusControl (Object): Optional control to focus on error
' **Returns**: Boolean - True if field has value, False if empty
' **Dependencies**: None
' **Side Effects**: Shows MsgBox popup on validation failure
' **Errors**: Returns False on validation failure
Public Function ValidateRequired(fieldValue As Variant, fieldName As String, Optional setFocusControl As Object = Nothing) As Boolean
    ValidateRequired = True

    If IsNull(fieldValue) Or Trim(CStr(fieldValue)) = "" Then
        MsgBox "Please enter " & fieldName & ".", vbExclamation + vbOKOnly, "Required Field Missing"
        If Not setFocusControl Is Nothing Then setFocusControl.SetFocus
        ValidateRequired = False
    End If
End Function

' **Purpose**: Validates numeric field and shows popup if invalid
' **Parameters**:
'   - fieldValue (Variant): Value to validate
'   - fieldName (String): Display name for field in error message
'   - setFocusControl (Object): Optional control to focus on error
' **Returns**: Boolean - True if field is numeric, False if invalid
' **Dependencies**: None
' **Side Effects**: Shows MsgBox popup on validation failure
' **Errors**: Returns False on validation failure
Public Function ValidateNumeric(fieldValue As Variant, fieldName As String, Optional setFocusControl As Object = Nothing) As Boolean
    ValidateNumeric = True

    If Not IsNumeric(fieldValue) Or Trim(CStr(fieldValue)) = "" Then
        MsgBox fieldName & " must be a valid number.", vbExclamation + vbOKOnly, "Invalid Number"
        If Not setFocusControl Is Nothing Then setFocusControl.SetFocus
        ValidateNumeric = False
    End If
End Function

' **Purpose**: Validates positive number field and shows popup if invalid
' **Parameters**:
'   - fieldValue (Variant): Value to validate
'   - fieldName (String): Display name for field in error message
'   - setFocusControl (Object): Optional control to focus on error
' **Returns**: Boolean - True if field is positive number, False if invalid
' **Dependencies**: ValidateNumeric
' **Side Effects**: Shows MsgBox popup on validation failure
' **Errors**: Returns False on validation failure
Public Function ValidatePositiveNumber(fieldValue As Variant, fieldName As String, Optional setFocusControl As Object = Nothing) As Boolean
    ValidatePositiveNumber = True

    If Not ValidateNumeric(fieldValue, fieldName, setFocusControl) Then
        ValidatePositiveNumber = False
        Exit Function
    End If

    If CDbl(fieldValue) <= 0 Then
        MsgBox fieldName & " must be greater than zero.", vbExclamation + vbOKOnly, "Invalid Value"
        If Not setFocusControl Is Nothing Then setFocusControl.SetFocus
        ValidatePositiveNumber = False
    End If
End Function

' **Purpose**: Validates list selection and shows popup if none selected
' **Parameters**:
'   - listControl (Object): ListBox or ComboBox control to validate
'   - fieldName (String): Display name for field in error message
' **Returns**: Boolean - True if selection made, False if no selection
' **Dependencies**: None
' **Side Effects**: Shows MsgBox popup on validation failure, sets focus to control
' **Errors**: Returns False on validation failure
Public Function ValidateListSelection(listControl As Object, fieldName As String) As Boolean
    ValidateListSelection = True

    If listControl.ListIndex < 0 Then
        MsgBox "Please select a " & fieldName & ".", vbExclamation + vbOKOnly, "Selection Required"
        listControl.SetFocus
        ValidateListSelection = False
    End If
End Function

' **Purpose**: Validates date field and shows popup if invalid
' **Parameters**:
'   - fieldValue (Variant): Value to validate as date
'   - fieldName (String): Display name for field in error message
'   - setFocusControl (Object): Optional control to focus on error
' **Returns**: Boolean - True if valid date, False if invalid
' **Dependencies**: None
' **Side Effects**: Shows MsgBox popup on validation failure
' **Errors**: Returns False on validation failure
Public Function ValidateDate(fieldValue As Variant, fieldName As String, Optional setFocusControl As Object = Nothing) As Boolean
    ValidateDate = True

    If Not IsDate(fieldValue) Then
        MsgBox fieldName & " must be a valid date.", vbExclamation + vbOKOnly, "Invalid Date"
        If Not setFocusControl Is Nothing Then setFocusControl.SetFocus
        ValidateDate = False
    End If
End Function

' **Purpose**: Show validation error with custom message
' **Parameters**:
'   - message (String): Custom validation error message
'   - title (String): Title for the error dialog
'   - setFocusControl (Object): Optional control to set focus to
' **Returns**: None (Subroutine)
' **Dependencies**: None
' **Side Effects**: Shows error dialog, sets focus to control if provided
' **CLAUDE.md Compliance**: Enhanced validation popup functionality
Public Sub ShowValidationError(message As String, title As String, Optional setFocusControl As Object = Nothing)
    MsgBox message, vbExclamation + vbOKOnly, title
    If Not setFocusControl Is Nothing Then setFocusControl.SetFocus
End Sub

' **Purpose**: Validates file exists and shows popup if missing
' **Parameters**:
'   - filePath (String): Full path to file to check
'   - fieldName (String): Display name for field in error message
' **Returns**: Boolean - True if file exists, False if missing
' **Dependencies**: None
' **Side Effects**: Shows MsgBox popup on validation failure
' **Errors**: Returns False on validation failure or file access error
Public Function ValidateFileExists(filePath As String, fieldName As String) As Boolean
    ValidateFileExists = True

    On Error GoTo FileError

    If Trim(filePath) = "" Or Dir(filePath) = "" Then
        MsgBox "The file specified for " & fieldName & " does not exist." & vbCrLf & "Path: " & filePath, vbExclamation + vbOKOnly, "File Not Found"
        ValidateFileExists = False
    End If

    Exit Function

FileError:
    MsgBox "Cannot access file for " & fieldName & "." & vbCrLf & "Path: " & filePath, vbCritical + vbOKOnly, "File Access Error"
    ValidateFileExists = False
End Function

' **Purpose**: Shows confirmation dialog with Yes/No options
' **Parameters**:
'   - message (String): Message to display
'   - title (String): Dialog title
' **Returns**: Boolean - True if user clicked Yes, False if No
' **Dependencies**: None
' **Side Effects**: Shows MsgBox confirmation dialog
' **Errors**: Returns False if dialog fails
Public Function ShowConfirmation(message As String, title As String) As Boolean
    ShowConfirmation = (MsgBox(message, vbYesNo + vbQuestion, title) = vbYes)
End Function

' **Purpose**: Validates special date caption (used in enquiry forms)
' **Parameters**:
'   - dateCaption (String): Caption text to check
'   - fieldName (String): Display name for field
' **Returns**: Boolean - True if user wants to continue without date, False to cancel
' **Dependencies**: ShowConfirmation
' **Side Effects**: Shows confirmation dialog for missing date
' **Errors**: Returns False if user cancels
Public Function ValidateSpecialDateCaption(dateCaption As String, fieldName As String) As Boolean
    ValidateSpecialDateCaption = True

    If dateCaption = "Please click here to insert a date" Then
        ValidateSpecialDateCaption = ShowConfirmation("No " & fieldName & " has been entered. Continue without date?", "Missing Date")
    End If
End Function

' **Purpose**: Validates WIP report form selections
' **Parameters**:
'   - ReportForm (Object): Form containing report selection controls (ROperation, ROperator, etc.)
' **Returns**: Boolean - True if at least one report type selected, False if none selected
' **Dependencies**: None
' **Side Effects**: Shows MsgBox popup if no selection made
' **CLAUDE.md Compliance**: Added for fwip.frm thin wrapper validation
Public Function ValidateReportSelection(ReportForm As Object) As Boolean
    ' **Updated for V2**: Allow no selection for basic WIP report (essential daily operations)
    ' Original validation only allowed Operation/Operator reports, but V2 supports basic WIP when no reports selected
    ValidateReportSelection = True ' Always validate successfully - let ReportingSystem handle the logic

    On Error GoTo Error_Handler
    Exit Function

Error_Handler:
    MsgBox "Error validating report selection: " & Err.Description, vbCritical, "Validation Error"
    ValidateReportSelection = False
End Function

' ===================================================================
' WORKFLOW-SPECIFIC VALIDATION FRAMEWORK (CLAUDE.md: Enhanced user guidance)
' ===================================================================

' **Purpose**: Validates that an enquiry is selected for quote conversion
' **Parameters**:
'   - ListForm (Object): Form containing enquiry list control
' **Returns**: Boolean - True if enquiry selected, False if no selection
' **Dependencies**: None
' **Side Effects**: Shows guidance popup on validation failure
' **Errors**: Returns False on validation failure
Public Function ValidateEnquirySelection(ListForm As Object) As Boolean
    ValidateEnquirySelection = True

    On Error GoTo Error_Handler

    If ListForm.lst.ListIndex < 0 Then
        ShowWorkflowGuidance "ConvertToQuote", "NoEnquirySelected"
        ValidateEnquirySelection = False
    End If

    Exit Function

Error_Handler:
    ValidateEnquirySelection = False
    LogError Err.Number, Err.Description, "ValidateEnquirySelection", "SystemCore"
End Function

' **Purpose**: Validates that a quote is selected for acceptance/submission
' **Parameters**:
'   - ListForm (Object): Form containing quote list control
' **Returns**: Boolean - True if quote selected, False if no selection
' **Dependencies**: None
' **Side Effects**: Shows guidance popup on validation failure
' **Errors**: Returns False on validation failure
Public Function ValidateQuoteSelection(ListForm As Object) As Boolean
    ValidateQuoteSelection = True

    On Error GoTo Error_Handler

    If ListForm.lst.ListIndex < 0 Then
        ShowWorkflowGuidance "AcceptQuote", "NoQuoteSelected"
        ValidateQuoteSelection = False
    End If

    Exit Function

Error_Handler:
    ValidateQuoteSelection = False
    LogError Err.Number, Err.Description, "ValidateQuoteSelection", "SystemCore"
End Function

' **Purpose**: Validates that a WIP job is selected for job card operations
' **Parameters**:
'   - ListForm (Object): Form containing WIP job list control
' **Returns**: Boolean - True if WIP job selected, False if no selection
' **Dependencies**: None
' **Side Effects**: Shows guidance popup on validation failure
' **Errors**: Returns False on validation failure
Public Function ValidateWIPJobSelection(ListForm As Object) As Boolean
    ValidateWIPJobSelection = True

    On Error GoTo Error_Handler

    If ListForm.lst.ListIndex < 0 Then
        ShowWorkflowGuidance "EditJobCard", "NoWIPJobSelected"
        ValidateWIPJobSelection = False
    End If

    Exit Function

Error_Handler:
    ValidateWIPJobSelection = False
    LogError Err.Number, Err.Description, "ValidateWIPJobSelection", "SystemCore"
End Function

' **Purpose**: Validates workflow prerequisites and guides user through proper steps
' **Parameters**:
'   - operation (String): Operation being attempted (ConvertToQuote, AcceptQuote, etc.)
'   - MainForm (Object): Main form containing list and checkbox controls
' **Returns**: Boolean - True if prerequisites met, False if validation fails
' **Dependencies**: Form checkbox states and list selections
' **Side Effects**: Shows guidance popup with next steps
' **Errors**: Returns False on validation failure
Public Function ValidateWorkflowPrerequisites(operation As String, MainForm As Object) As Boolean
    ValidateWorkflowPrerequisites = True

    On Error GoTo Error_Handler

    Select Case UCase(operation)
        Case "CONVERTTOQUOTE"
            ' Must have enquiries checkbox selected and enquiry selected
            If Not MainForm.Enquiries.Value Then
                ShowWorkflowGuidance "ConvertToQuote", "EnquiriesNotSelected"
                ValidateWorkflowPrerequisites = False
            ElseIf MainForm.lst.ListCount = 0 Then
                ShowWorkflowGuidance "ConvertToQuote", "ListEmpty"
                ValidateWorkflowPrerequisites = False
            ElseIf MainForm.lst.ListIndex < 0 Then
                ShowWorkflowGuidance "ConvertToQuote", "NoEnquirySelected"
                ValidateWorkflowPrerequisites = False
            End If

        Case "ACCEPTQUOTE"
            ' Must have quotes checkbox selected and quote selected
            If Not MainForm.Quotes.Value Then
                ShowWorkflowGuidance "AcceptQuote", "QuotesNotSelected"
                ValidateWorkflowPrerequisites = False
            ElseIf MainForm.lst.ListCount = 0 Then
                ShowWorkflowGuidance "AcceptQuote", "ListEmpty"
                ValidateWorkflowPrerequisites = False
            ElseIf MainForm.lst.ListIndex < 0 Then
                ShowWorkflowGuidance "AcceptQuote", "NoQuoteSelected"
                ValidateWorkflowPrerequisites = False
            End If

        Case "SUBMITQUOTE"
            ' Must have quotes checkbox selected and quote selected
            If Not MainForm.Quotes.Value Then
                ShowWorkflowGuidance "SubmitQuote", "QuotesNotSelected"
                ValidateWorkflowPrerequisites = False
            ElseIf MainForm.lst.ListCount = 0 Then
                ShowWorkflowGuidance "SubmitQuote", "ListEmpty"
                ValidateWorkflowPrerequisites = False
            ElseIf MainForm.lst.ListIndex < 0 Then
                ShowWorkflowGuidance "SubmitQuote", "NoQuoteSelected"
                ValidateWorkflowPrerequisites = False
            End If

        Case "EDITJOBCARD"
            ' Must have WIP or JobsInWIP checkbox selected and job selected
            If Not MainForm.WIP.Value And Not MainForm.JobsInWIP.Value Then
                ShowWorkflowGuidance "EditJobCard", "WIPNotSelected"
                ValidateWorkflowPrerequisites = False
            ElseIf MainForm.lst.ListCount = 0 Then
                ShowWorkflowGuidance "EditJobCard", "ListEmpty"
                ValidateWorkflowPrerequisites = False
            ElseIf MainForm.lst.ListIndex < 0 Then
                ShowWorkflowGuidance "EditJobCard", "NoWIPJobSelected"
                ValidateWorkflowPrerequisites = False
            End If

        Case "OPENJOB"
            ' Must have WIP or JobsInWIP checkbox selected and job selected
            If Not MainForm.WIP.Value And Not MainForm.JobsInWIP.Value Then
                ShowWorkflowGuidance "OpenJob", "WIPNotSelected"
                ValidateWorkflowPrerequisites = False
            ElseIf MainForm.lst.ListCount = 0 Then
                ShowWorkflowGuidance "OpenJob", "ListEmpty"
                ValidateWorkflowPrerequisites = False
            ElseIf MainForm.lst.ListIndex < 0 Then
                ShowWorkflowGuidance "OpenJob", "NoWIPJobSelected"
                ValidateWorkflowPrerequisites = False
            End If

        Case "CLOSEJOB"
            ' Must have WIP or JobsInWIP checkbox selected and job selected
            If Not MainForm.WIP.Value And Not MainForm.JobsInWIP.Value Then
                ShowWorkflowGuidance "CloseJob", "WIPNotSelected"
                ValidateWorkflowPrerequisites = False
            ElseIf MainForm.lst.ListCount = 0 Then
                ShowWorkflowGuidance "CloseJob", "ListEmpty"
                ValidateWorkflowPrerequisites = False
            ElseIf MainForm.lst.ListIndex < 0 Then
                ShowWorkflowGuidance "CloseJob", "NoWIPJobSelected"
                ValidateWorkflowPrerequisites = False
            End If
    End Select

    Exit Function

Error_Handler:
    ValidateWorkflowPrerequisites = False
    LogError Err.Number, Err.Description, "ValidateWorkflowPrerequisites", "SystemCore"
End Function

' **Purpose**: Show workflow guidance with next steps for users
' **Parameters**:
'   - operation (String): Operation being attempted
'   - currentState (String): Current state that caused validation failure
' **Returns**: None (Subroutine)
' **Dependencies**: None
' **Side Effects**: Displays detailed guidance popup with workflow steps
' **Errors**: None
Public Sub ShowWorkflowGuidance(operation As String, currentState As String)
    Dim GuidanceTitle As String
    Dim GuidanceMessage As String

    On Error Resume Next

    Select Case UCase(operation) & "_" & UCase(currentState)
        Case "CONVERTTOQUOTE_ENQUIRIESNOTSELECTED"
            GuidanceTitle = "Convert to Quote - Setup Required"
            GuidanceMessage = "To convert an enquiry to quote:" & vbCrLf & vbCrLf & _
                             "1. Click the 'Enquiries' checkbox" & vbCrLf & _
                             "2. Select an enquiry from the list" & vbCrLf & _
                             "3. Click 'Convert to Quote' again"

        Case "CONVERTTOQUOTE_NOENQUIRYSELECTED"
            GuidanceTitle = "Convert to Quote - Selection Required"
            GuidanceMessage = "Please select an enquiry from the list first." & vbCrLf & vbCrLf & _
                             "To convert an enquiry to quote:" & vbCrLf & _
                             "1. Select an enquiry from the current list" & vbCrLf & _
                             "2. Click 'Convert to Quote' again"

        Case "ACCEPTQUOTE_QUOTESNOTSELECTED"
            GuidanceTitle = "Accept Quote - Setup Required"
            GuidanceMessage = "To accept a quote:" & vbCrLf & vbCrLf & _
                             "1. Click the 'Quotes' checkbox" & vbCrLf & _
                             "2. Select a quote from the list" & vbCrLf & _
                             "3. Click 'Accept Quote' again"

        Case "ACCEPTQUOTE_NOQUOTESELECTED"
            GuidanceTitle = "Accept Quote - Selection Required"
            GuidanceMessage = "Please select a quote from the list first." & vbCrLf & vbCrLf & _
                             "To accept a quote:" & vbCrLf & _
                             "1. Select a quote from the current list" & vbCrLf & _
                             "2. Click 'Accept Quote' again"

        Case "SUBMITQUOTE_QUOTESNOTSELECTED"
            GuidanceTitle = "Submit Quote - Setup Required"
            GuidanceMessage = "To submit a quote:" & vbCrLf & vbCrLf & _
                             "1. Click the 'Quotes' checkbox" & vbCrLf & _
                             "2. Select a quote from the list" & vbCrLf & _
                             "3. Click 'Submit Quote' again"

        Case "SUBMITQUOTE_NOQUOTESELECTED"
            GuidanceTitle = "Submit Quote - Selection Required"
            GuidanceMessage = "Please select a quote from the list first." & vbCrLf & vbCrLf & _
                             "To submit a quote:" & vbCrLf & _
                             "1. Select a quote from the current list" & vbCrLf & _
                             "2. Click 'Submit Quote' again"

        Case "EDITJOBCARD_WIPNOTSELECTED"
            GuidanceTitle = "Edit Job Card - Setup Required"
            GuidanceMessage = "To edit a job card:" & vbCrLf & vbCrLf & _
                             "1. Click the 'WIP' checkbox" & vbCrLf & _
                             "2. Select a WIP job from the list" & vbCrLf & _
                             "3. Click 'Edit Job Card' again"

        Case "EDITJOBCARD_NOWIPJOBSELECTED"
            GuidanceTitle = "Edit Job Card - Selection Required"
            GuidanceMessage = "Please select a WIP job from the list first." & vbCrLf & vbCrLf & _
                             "To edit a job card:" & vbCrLf & _
                             "1. Select a WIP job from the current list" & vbCrLf & _
                             "2. Click 'Edit Job Card' again"

        Case "OPENJOB_WIPNOTSELECTED"
            GuidanceTitle = "Open Job - Setup Required"
            GuidanceMessage = "To open a job:" & vbCrLf & vbCrLf & _
                             "1. Click the 'WIP' checkbox" & vbCrLf & _
                             "2. Select a WIP job from the list" & vbCrLf & _
                             "3. Click 'Open Job' again"

        Case "OPENJOB_NOWIPJOBSELECTED"
            GuidanceTitle = "Open Job - Selection Required"
            GuidanceMessage = "Please select a WIP job from the list first." & vbCrLf & vbCrLf & _
                             "To open a job:" & vbCrLf & _
                             "1. Select a WIP job from the current list" & vbCrLf & _
                             "2. Click 'Open Job' again"

        Case "CLOSEJOB_WIPNOTSELECTED"
            GuidanceTitle = "Close Job - Setup Required"
            GuidanceMessage = "To close a job:" & vbCrLf & vbCrLf & _
                             "1. Click the 'WIP' checkbox" & vbCrLf & _
                             "2. Select a WIP job from the list" & vbCrLf & _
                             "3. Click 'Close Job' again"

        Case "CLOSEJOB_NOWIPJOBSELECTED"
            GuidanceTitle = "Close Job - Selection Required"
            GuidanceMessage = "Please select a WIP job from the list first." & vbCrLf & vbCrLf & _
                             "To close a job:" & vbCrLf & _
                             "1. Select a WIP job from the current list" & vbCrLf & _
                             "2. Click 'Close Job' again"

        Case "CONVERTTOQUOTE_LISTEMPTY"
            GuidanceTitle = "Convert to Quote - No Enquiries Found"
            GuidanceMessage = "No enquiries are currently displayed." & vbCrLf & vbCrLf & _
                             "To convert an enquiry to quote:" & vbCrLf & _
                             "1. Click the 'Enquiries' checkbox to load enquiries" & vbCrLf & _
                             "2. Select an enquiry from the list" & vbCrLf & _
                             "3. Click 'Convert to Quote' again"

        Case "ACCEPTQUOTE_LISTEMPTY"
            GuidanceTitle = "Accept Quote - No Quotes Found"
            GuidanceMessage = "No quotes are currently displayed." & vbCrLf & vbCrLf & _
                             "To accept a quote:" & vbCrLf & _
                             "1. Click the 'Quotes' checkbox to load quotes" & vbCrLf & _
                             "2. Select a quote from the list" & vbCrLf & _
                             "3. Click 'Accept Quote' again"

        Case "SUBMITQUOTE_LISTEMPTY"
            GuidanceTitle = "Submit Quote - No Quotes Found"
            GuidanceMessage = "No quotes are currently displayed." & vbCrLf & vbCrLf & _
                             "To submit a quote:" & vbCrLf & _
                             "1. Click the 'Quotes' checkbox to load quotes" & vbCrLf & _
                             "2. Select a quote from the list" & vbCrLf & _
                             "3. Click 'Submit Quote' again"

        Case "EDITJOBCARD_LISTEMPTY"
            GuidanceTitle = "Edit Job Card - No WIP Jobs Found"
            GuidanceMessage = "No WIP jobs are currently displayed." & vbCrLf & vbCrLf & _
                             "To edit a job card:" & vbCrLf & _
                             "1. Click the 'WIP' checkbox to load WIP jobs" & vbCrLf & _
                             "2. Select a WIP job from the list" & vbCrLf & _
                             "3. Click 'Edit Job Card' again"

        Case "OPENJOB_LISTEMPTY"
            GuidanceTitle = "Open Job - No WIP Jobs Found"
            GuidanceMessage = "No WIP jobs are currently displayed." & vbCrLf & vbCrLf & _
                             "To open a job:" & vbCrLf & _
                             "1. Click the 'WIP' checkbox to load WIP jobs" & vbCrLf & _
                             "2. Select a WIP job from the list" & vbCrLf & _
                             "3. Click 'Open Job' again"

        Case "CLOSEJOB_LISTEMPTY"
            GuidanceTitle = "Close Job - No WIP Jobs Found"
            GuidanceMessage = "No WIP jobs are currently displayed." & vbCrLf & vbCrLf & _
                             "To close a job:" & vbCrLf & _
                             "1. Click the 'WIP' checkbox to load WIP jobs" & vbCrLf & _
                             "2. Select a WIP job from the list" & vbCrLf & _
                             "3. Click 'Close Job' again"

        Case Else
            GuidanceTitle = "Operation Guidance"
            GuidanceMessage = "Please ensure you have selected the appropriate item before performing this operation."
    End Select

    MsgBox GuidanceMessage, vbInformation + vbOKOnly, GuidanceTitle
    On Error GoTo 0
End Sub

' **Purpose**: Validates that the list contains items before allowing operations
' **Parameters**:
'   - ListForm (Object): Form containing list control
'   - operation (String): Operation being attempted
' **Returns**: Boolean - True if list has items, False if empty
' **Dependencies**: None
' **Side Effects**: Shows guidance popup if list is empty
' **Errors**: Returns False if list is empty
Public Function ValidateListHasItems(ListForm As Object, operation As String) As Boolean
    ValidateListHasItems = True

    On Error GoTo Error_Handler

    If ListForm.lst.ListCount = 0 Then
        ShowWorkflowGuidance operation, "ListEmpty"
        ValidateListHasItems = False
    End If

    Exit Function

Error_Handler:
    ValidateListHasItems = False
    LogError Err.Number, Err.Description, "ValidateListHasItems", "SystemCore"
End Function

' ===================================================================
' LEGACY COMPATIBILITY FUNCTIONS (CLAUDE.md: Maintain backward compatibility)
' ===================================================================

' **Purpose**: Legacy wrapper for RemoveInvalidCharacters function
' **Parameters**:
'   - Str (String): String to process
' **Returns**: String - String with invalid characters removed
' **Dependencies**: RemoveInvalidCharacters
' **Side Effects**: None
' **Errors**: Returns empty string if input is empty
' **CLAUDE.md Compliance**: Maintains compatibility with legacy form code
Public Function Remove_Characters(ByVal Str As String) As String
    Remove_Characters = RemoveInvalidCharacters(Str)
End Function

' **Purpose**: Legacy wrapper for FormatDisplayText function
' **Parameters**:
'   - Str (String): String to format for display
' **Returns**: String - Formatted string with improved readability
' **Dependencies**: FormatDisplayText
' **Side Effects**: None
' **Errors**: Returns empty string if input is empty
' **CLAUDE.md Compliance**: Maintains compatibility with legacy form code
Public Function Insert_Characters(ByVal Str As String) As String
    Insert_Characters = FormatDisplayText(Str)
End Function

